
baseURL = "https://starrydash.com/"
languageCode = "en-us"
title = "StarryDash"
theme = "ananke"

enableRobotsTXT = true
buildFuture = false

[pagination]
pagerSize = 10
[params]
  mainSections = ["posts"]
